# Generated by Django 4.2.2 on 2023-07-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='envio',
            field=models.CharField(choices=[('Domicilio', 'Domicilio'), ('Recoge en punto', 'Recoge en punto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En ruta', 'En ruta'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
